services:
  - type: web
    name: hnd-platform-backend
    env: docker
    rootDir: hnd_backend
    dockerfilePath: Dockerfile
    autoDeploy: true
    plan: free
    envVars:
      - key: LIBREOFFICE_PATH
        value: /usr/bin/soffice

  - type: web
    name: hnd-platform-converter
    env: docker
    rootDir: docker_converter
    dockerfilePath: Dockerfile
    autoDeploy: true
    plan: free
    envVars:
      - key: LIBREOFFICE_PATH
        value: /usr/bin/soffice
