const express = require('express');
const router = express.Router();
const { requireAuth } = require('../middlewares/jwtAuth');
const { requireConcoursRole, requireActivePartnership } = require('../middlewares/concoursAuthorization');
const controller = require('../controllers/concoursController');
const partnerController = require('../controllers/concoursPartnerController');
const { requireDeveloper } = require('../middlewares/jwtAuth');
const multer = require('multer');
const path = require('path');
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 20 * 1024 * 1024 }, fileFilter: (_req, file, cb) => { const allowed = ['.pdf', '.doc', '.docx', '.jpg', '.jpeg', '.png']; cb(allowed.includes(path.extname(file.originalname).toLowerCase()) ? null : new Error('Unsupported file type'), allowed.includes(path.extname(file.originalname).toLowerCase())); } });

router.use(requireAuth);
router.get('/', requireConcoursRole(['candidate', 'concour_partner', 'admin', 'developer', 'superadmin']), controller.list);
router.get('/applications', requireConcoursRole(['candidate']), controller.myApplications);
router.get('/partner/concours', requireConcoursRole(['concour_partner', 'admin', 'developer', 'superadmin']), controller.partnerList);
router.get('/partner/concours/:id', requireConcoursRole(['concour_partner', 'admin', 'developer', 'superadmin']), controller.getManaged);
router.get('/partner/status', requireConcoursRole(['concour_partner']), partnerController.status);
router.post('/partner/agreement/accept', requireConcoursRole(['concour_partner']), partnerController.acceptAgreement);
router.post('/partner/payment/checkout', requireConcoursRole(['concour_partner']), partnerController.checkout);
router.get('/developer/partners', requireDeveloper, partnerController.list);
router.post('/developer/partners', requireDeveloper, partnerController.create);
router.patch('/developer/partners/:partnerId/status', requireDeveloper, partnerController.setStatus);
router.put('/developer/partners/:partnerId', requireDeveloper, partnerController.update);
router.put('/developer/partners/:partnerId/assign-admin', requireDeveloper, partnerController.assignAdmin);
router.get('/partner/applications', requireConcoursRole(['concour_partner', 'admin', 'developer', 'superadmin']), controller.applications);
router.post('/partner/concours', requireConcoursRole(['concour_partner', 'admin', 'developer', 'superadmin']), requireActivePartnership, controller.create);
router.put('/partner/concours/:id', requireConcoursRole(['concour_partner', 'admin', 'developer', 'superadmin']), requireActivePartnership, controller.update);
router.delete('/partner/concours/:id', requireDeveloper, controller.deleteConcours);
router.put('/partner/concours/:id/form', requireConcoursRole(['concour_partner', 'admin', 'developer', 'superadmin']), requireActivePartnership, controller.saveForm);
router.post('/partner/concours/:id/form/publish', requireDeveloper, controller.publishForm);
router.post('/partner/concours/:id/publish', requireDeveloper, controller.publishConcours);
router.patch('/partner/concours/:id/unpublish', requireDeveloper, controller.unpublishConcours);
router.post('/partner/concours/:id/unpublish-request', requireConcoursRole(['concour_partner']), requireActivePartnership, controller.requestUnpublish);
router.patch('/partner/applications/:applicationId', requireConcoursRole(['concour_partner', 'admin', 'developer', 'superadmin']), requireActivePartnership, controller.updateApplication);
router.get('/:id', requireConcoursRole(['candidate', 'concour_partner', 'admin', 'developer', 'superadmin']), controller.get);
router.post('/:id/applications', requireConcoursRole(['candidate']), controller.apply);
router.put('/:id/applications/draft', requireConcoursRole(['candidate']), controller.saveDraft);
router.post('/applications/:applicationId/resubmit', requireConcoursRole(['candidate']), controller.resubmit);
router.post('/applications/:applicationId/documents', requireConcoursRole(['candidate']), upload.single('file'), controller.uploadDocument);
router.get('/applications/:applicationId/documents/:documentId', requireConcoursRole(['candidate', 'concour_partner', 'admin', 'developer', 'superadmin']), controller.downloadDocument);
module.exports = router;
