const Concours = require('../models/Concours');
const ConcoursApplication = require('../models/ConcoursApplication');
const User = require('../models/User');
const { listPublicConcours, createApplication, validateForm } = require('../services/concoursService');
const { isDeveloper, isPartner, canAccessPartner } = require('../middlewares/concoursAuthorization');
const { uploadFile, getS3ObjectStream } = require('../utils/s3Uploader');
const { sendEmail } = require('../services/emailService');

const actor = (req) => String(req.user?.cand_id || 'system');
const partnerIdForRequest = async (req) => {
  if (isDeveloper(req) || String(req.user?.role || '').toLowerCase() === 'admin') return req.body?.partnerId;
  const user = await User.findOne({ cand_id: req.user.cand_id }).select('_id').lean();
  return user?._id;
};

exports.list = async (req, res, next) => { try { return res.json({ success: true, ...(await listPublicConcours(req.query)) }); } catch (err) { return next(err); } };
exports.get = async (req, res, next) => { try { const item = await Concours.findOne({ _id: req.params.id, status: { $in: ['published', 'closed'] } }).lean(); if (!item) return res.status(404).json({ success: false, message: 'Concours not found' }); return res.json({ success: true, concours: item }); } catch (err) { return next(err); } };
exports.getManaged = async (req, res, next) => { try { const item = await Concours.findById(req.params.id).lean(); if (!item || !(await canAccessPartner(req, item.partnerId))) return res.status(403).json({ success: false, message: 'Concours access denied' }); return res.json({ success: true, concours: item }); } catch (err) { return next(err); } };
exports.apply = async (req, res, next) => { try { const application = await createApplication(req.params.id, req); return res.status(201).json({ success: true, application }); } catch (err) { return res.status(err.statusCode || 500).json({ success: false, message: err.message }); } };
exports.myApplications = async (req, res, next) => { try { const applications = await ConcoursApplication.find({ candidateCandId: req.user.cand_id }).populate('concoursId', 'title organizationName closingDate').sort({ createdAt: -1 }).lean(); return res.json({ success: true, applications }); } catch (err) { return next(err); } };
exports.saveDraft = async (req, res, next) => { try { const concours = await Concours.findById(req.params.id).select('partnerId'); const user = await User.findOne({ cand_id: req.user.cand_id }).select('_id cand_id name email phone address program profile_picture').lean(); if (!concours || !user) return res.status(404).json({ success: false, message: 'Concours or candidate not found' }); const application = await ConcoursApplication.findOneAndUpdate({ candidateId: user._id, concoursId: concours._id }, { $set: { partnerId: concours.partnerId, candidateCandId: user.cand_id, answers: req.body?.answers || {}, profileSnapshot: { name: user.name, email: user.email, phone: user.phone, address: user.address, program: user.program, profile_picture: user.profile_picture } }, $setOnInsert: { status: 'draft', timeline: [{ status: 'draft', actorId: user.cand_id }] } }, { upsert: true, new: true, setDefaultsOnInsert: true }); return res.json({ success: true, application }); } catch (err) { return next(err); } };
exports.resubmit = async (req, res, next) => { try { const application = await ConcoursApplication.findOne({ _id: req.params.applicationId, candidateCandId: req.user.cand_id }); if (!application || application.status !== 'correction_requested') return res.status(400).json({ success: false, message: 'Only applications requesting correction can be resubmitted' }); const concours = await Concours.findById(application.concoursId).select('closingDate'); if (!concours || new Date(concours.closingDate) < new Date()) return res.status(400).json({ success: false, message: 'Application deadline has passed' }); application.answers = req.body?.answers || application.answers; application.status = 'resubmitted'; application.resubmittedAt = new Date(); application.timeline.push({ status: 'resubmitted', actorId: req.user.cand_id }); await application.save(); return res.json({ success: true, application }); } catch (err) { return next(err); } };

exports.partnerList = async (req, res, next) => { try { const user = await User.findOne({ cand_id: req.user.cand_id }).select('_id').lean(); let filter = {}; if (isPartner(req)) filter.partnerId = user?._id; if (String(req.user?.role || '').toLowerCase() === 'admin') { const assignments = await require('../models/ConcoursAssignment').find({ adminId: user?._id, active: true }).select('partnerId').lean(); filter.partnerId = { $in: assignments.map((item) => item.partnerId) }; } const concours = await Concours.find(filter).sort({ createdAt: -1 }).lean(); return res.json({ success: true, concours }); } catch (err) { return next(err); } };
exports.create = async (req, res, next) => { try { const partnerId = await partnerIdForRequest(req); if (!partnerId || !(await canAccessPartner(req, partnerId))) return res.status(403).json({ success: false, message: 'Partner access denied' }); const payload = { ...req.body, partnerId, createdBy: actor(req), updatedBy: actor(req) }; const concours = await Concours.create(payload); if (isPartner(req)) { try { const reviewers = await User.find({ role: 'superadmin', account_status: 'active' }).select('email').lean(); await Promise.all(reviewers.filter((reviewer) => reviewer.email).map((reviewer) => sendEmail({ to: reviewer.email, subject: `Concours draft submitted: ${concours.title}`, text: [`A new concours draft has been submitted for review.`, `Title: ${concours.title}`, `Organization: ${concours.organizationName}`, `Opening date: ${new Date(concours.openingDate).toLocaleDateString()}`, `Closing date: ${new Date(concours.closingDate).toLocaleDateString()}`, '', 'Please sign in to ACADEX to review and publish it.'].join('\n') }))); } catch (emailError) { console.error('[Concours] Review notification email failed:', emailError.message); } } return res.status(201).json({ success: true, concours }); } catch (err) { return next(err); } };
exports.update = async (req, res, next) => { try { const concours = await Concours.findById(req.params.id); if (!concours || !(await canAccessPartner(req, concours.partnerId))) return res.status(403).json({ success: false, message: 'Concours access denied' }); const updates = { ...req.body, partnerId: concours.partnerId, updatedBy: actor(req) }; delete updates.createdBy; if (updates.applicationForm) validateForm(updates.applicationForm); Object.assign(concours, updates); await concours.save(); return res.json({ success: true, concours }); } catch (err) { return next(err); } };
exports.saveForm = async (req, res, next) => { try { const concours = await Concours.findById(req.params.id); if (!concours || !(await canAccessPartner(req, concours.partnerId))) return res.status(403).json({ success: false, message: 'Concours access denied' }); validateForm(req.body); concours.applicationForm = { ...req.body, version: Number(concours.applicationForm?.version || 0) + 1, published: false }; concours.updatedBy = actor(req); await concours.save(); return res.json({ success: true, form: concours.applicationForm }); } catch (err) { return res.status(400).json({ success: false, message: err.message }); } };
exports.publishForm = async (req, res, next) => { try { const concours = await Concours.findById(req.params.id); if (!concours || !(await canAccessPartner(req, concours.partnerId))) return res.status(403).json({ success: false, message: 'Concours access denied' }); validateForm(concours.applicationForm); if (!concours.applicationForm.fields.length) return res.status(400).json({ success: false, message: 'Add at least one application field before publishing' }); concours.applicationForm.published = true; concours.applicationForm.publishedAt = new Date(); concours.updatedBy = actor(req); await concours.save(); return res.json({ success: true, form: concours.applicationForm }); } catch (err) { return res.status(400).json({ success: false, message: err.message }); } };
exports.publishConcours = async (req, res, next) => { try { const concours = await Concours.findById(req.params.id); if (!concours || !(await canAccessPartner(req, concours.partnerId))) return res.status(403).json({ success: false, message: 'Concours access denied' }); if (!concours.applicationForm?.published) return res.status(400).json({ success: false, message: 'Publish the application form first' }); if (new Date(concours.closingDate) <= new Date()) return res.status(400).json({ success: false, message: 'Closing date must be in the future' }); concours.status = 'published'; concours.updatedBy = actor(req); await concours.save(); return res.json({ success: true, concours }); } catch (err) { return next(err); } };
exports.unpublishConcours = async (req, res, next) => { try { const concours = await Concours.findById(req.params.id); if (!concours || !(await canAccessPartner(req, concours.partnerId))) return res.status(403).json({ success: false, message: 'Concours access denied' }); concours.status = 'draft'; concours.updatedBy = actor(req); await concours.save(); return res.json({ success: true, concours }); } catch (err) { return next(err); } };
exports.requestUnpublish = async (req, res, next) => { try { const concours = await Concours.findById(req.params.id); if (!concours || !(await canAccessPartner(req, concours.partnerId))) return res.status(403).json({ success: false, message: 'Concours access denied' }); if (concours.status !== 'published') return res.status(400).json({ success: false, message: 'Only published concours can be requested for unpublishing' }); const partner = await User.findById(concours.partnerId).select('organization name email').lean(); const reviewers = await User.find({ role: { $in: ['developer', 'superadmin'] }, account_status: 'active' }).select('email').lean(); await Promise.all(reviewers.filter((reviewer) => reviewer.email).map((reviewer) => sendEmail({ to: reviewer.email, subject: `Unpublish request: ${concours.title}`, text: [`A partner requested that this concours be unpublished.`, `Title: ${concours.title}`, `Organization: ${concours.organizationName}`, `Partner: ${partner?.organization?.name || partner?.name || partner?.email || 'Unknown'}`, `Reason: ${String(req.body?.reason || 'No reason provided').trim()}`, '', 'Review the request in ACADEX developer management.'].join('\n') }))); await ConcoursAuditLog.create({ event: 'concours.unpublish.requested', actorId: actor(req), partnerId: concours.partnerId, concoursId: concours._id, metadata: { reason: String(req.body?.reason || '').trim() } }); return res.json({ success: true, message: 'Unpublish request sent to the developer team.' }); } catch (err) { return next(err); } };
exports.deleteConcours = async (req, res, next) => { try { const concours = await Concours.findById(req.params.id); if (!concours || !(await canAccessPartner(req, concours.partnerId))) return res.status(403).json({ success: false, message: 'Concours access denied' }); await Promise.all([Concours.deleteOne({ _id: concours._id }), ConcoursApplication.deleteMany({ concoursId: concours._id })]); return res.json({ success: true }); } catch (err) { return next(err); } };
exports.applications = async (req, res, next) => { try { const user = await User.findOne({ cand_id: req.user.cand_id }).select('_id').lean(); let filter = {}; if (isPartner(req)) filter.partnerId = user?._id; if (String(req.user?.role || '').toLowerCase() === 'admin') { const assignments = await require('../models/ConcoursAssignment').find({ adminId: user?._id, active: true }).select('partnerId').lean(); filter.partnerId = { $in: assignments.map((item) => item.partnerId) }; } const applications = await ConcoursApplication.find(filter).populate('concoursId', 'title organizationName').sort({ submittedAt: -1 }).limit(100).lean(); return res.json({ success: true, applications }); } catch (err) { return next(err); } };
exports.updateApplication = async (req, res, next) => { try { const application = await ConcoursApplication.findById(req.params.applicationId); if (!application || !(await canAccessPartner(req, application.partnerId))) return res.status(403).json({ success: false, message: 'Application access denied' }); const allowed = ['received', 'under_review', 'shortlisted', 'rejected', 'selected', 'correction_requested', 'forwarded']; if (!allowed.includes(req.body?.status)) return res.status(400).json({ success: false, message: 'Invalid application status' }); application.status = req.body.status; application.correctionReason = req.body.status === 'correction_requested' ? String(req.body.reason || '').trim() : application.correctionReason; application.correctionRequestedAt = req.body.status === 'correction_requested' ? new Date() : application.correctionRequestedAt; application.timeline.push({ status: application.status, note: req.body.reason || '', actorId: actor(req) }); await application.save(); return res.json({ success: true, application }); } catch (err) { return next(err); } };
exports.uploadDocument = async (req, res, next) => { try { if (!req.file) return res.status(400).json({ success: false, message: 'File is required' }); const application = await ConcoursApplication.findById(req.params.applicationId).populate('concoursId', 'closingDate'); if (!application || String(application.candidateCandId) !== String(req.user.cand_id)) return res.status(403).json({ success: false, message: 'Application access denied' }); if (new Date(application.concoursId?.closingDate) < new Date()) return res.status(400).json({ success: false, message: 'The application deadline has passed' }); const upload = await uploadFile(req.file.buffer, req.file.originalname, req.file.mimetype, 'concours-applications'); application.documents.push({ fieldId: String(req.body?.fieldId || '').trim(), originalName: String(req.file.originalname || '').replace(/[\\/]/g, '_'), storageKey: upload.key, mimeType: req.file.mimetype, size: req.file.size }); await application.save(); return res.status(201).json({ success: true, document: application.documents[application.documents.length - 1] }); } catch (err) { return next(err); } };
exports.downloadDocument = async (req, res, next) => { try { const application = await ConcoursApplication.findById(req.params.applicationId).select('candidateCandId partnerId documents').lean(); if (!application) return res.status(404).json({ success: false, message: 'Application not found' }); const authorized = String(application.candidateCandId) === String(req.user.cand_id) || await canAccessPartner(req, application.partnerId); if (!authorized) return res.status(403).json({ success: false, message: 'Document access denied' }); const document = application.documents.find((item) => String(item._id) === String(req.params.documentId)); if (!document) return res.status(404).json({ success: false, message: 'Document not found' }); res.setHeader('Content-Type', document.mimeType); res.setHeader('Content-Disposition', `attachment; filename="${String(document.originalName).replace(/[^a-zA-Z0-9._-]/g, '_')}"`); const stream = getS3ObjectStream(document.storageKey); stream.on('missing', () => { if (!res.headersSent) res.status(404).json({ success: false, message: 'Stored document not found' }); }); stream.on('error', next); stream.pipe(res); } catch (err) { return next(err); } };
